### ISSUE TITLE
getWeatherInDays test fails

### ISSUE THREAD

**Issue by 101hawn** [ZGoriely/Weather#27]

**Comment by SlightlySwissGuy** [comment]
Hmm
I noticed just now that the dates are wrong on the DaysScreen branch
Wonder if this is linked. I'll have a look. This is on develop right?

**Comment by SlightlySwissGuy** [comment]
Well of course it fails!
Read the error message
You got a CrystalBallDepthExceededException
You tried to get a reading we don't have

**Comment by SlightlySwissGuy** [comment]
I should potentially add a function you can call to check if a certain reading is available though to be fair..

**Comment by SlightlySwissGuy** [comment]
I'll get on that

**Comment by SlightlySwissGuy** [comment]
We now have a static method:
boolean forecastAvailable(int days, int timeInHours)
That does the range checking to calculate whether a given weather forecast time should be available. The tests and the DaysViewModelSource should use this to check if forecasts are available (for example, if it is 7am, we only have the forecasts up to 6am 5 days in the future etc)

**Comment by SlightlySwissGuy** [comment]
Oh it was my test lolololololol

**Comment by SlightlySwissGuy** [comment]
Turns out that was a deliberate fail
Changed it now tho
