### ISSUE TITLE
Code isn't commented to death

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#35]

**Comment by ZGoriely** [comment]
goodness

**Comment by ivanmgribeiro** [comment]
Classes not yet commented:
SlidingPanel
StyleManager
GroupableTableHeaderUI

**Comment by SlightlySwissGuy** [comment]
Impressively small list

**Comment by 101hawn** [comment]
SlidingPanel: 8e56b5f9f27ce5863ca7fe2c4f073e831b3436ae
StyleManager: d5bad58d5e404590d1840c3fab294b90ce5758c0


GroupableTableHeaderUI: TODO

**Comment by ZGoriely** [comment]
who made that class?

**Comment by EmptyJackson** [comment]
Me, got it from the internet as it turns out grouping table headers in jtables is near impossible. I'll try commenting that if no one has yet as it might be nasty
