### ISSUE TITLE
Can someone check my instructions work?

### ISSUE THREAD

**Issue by 101hawn** [ZGoriely/Weather#38]
Test from git clone to run please. Probably a Linux person

**Comment by SlightlySwissGuy** [comment]
Sure theng

**Comment by SlightlySwissGuy** [comment]
Where these?

**Comment by 101hawn** [comment]
README

**Comment by SlightlySwissGuy** [comment]
Installed gradle 4.7
Redid git clone etc
The build went fine:


> Task :compileJava
/home/dave/prog_code/CamCompSci/ID/project/Testing/readme_test/Weather/src/main/java/uk/ac/cam/groupseven/weatherapp/ScreenLayout.java:7: warning: NotImplementedException is internal proprietary API and may be removed in a future release
import sun.reflect.generics.reflectiveObjects.NotImplementedException;
                                             ^
/home/dave/prog_code/CamCompSci/ID/project/Testing/readme_test/Weather/src/main/java/uk/ac/cam/groupseven/weatherapp/datasources/OpenWeatherSource.java:11: warning: NotImplementedException is internal proprietary API and may be removed in a future release
import sun.reflect.generics.reflectiveObjects.NotImplementedException;
                                             ^
/home/dave/prog_code/CamCompSci/ID/project/Testing/readme_test/Weather/src/main/java/uk/ac/cam/groupseven/weatherapp/screens/MoreScreen.java:6: warning: NotImplementedException is internal proprietary API and may be removed in a future release
import sun.reflect.generics.reflectiveObjects.NotImplementedException;
                                             ^
/home/dave/prog_code/CamCompSci/ID/project/Testing/readme_test/Weather/src/main/java/uk/ac/cam/groupseven/weatherapp/ScreenLayout.java:106: warning: NotImplementedException is internal proprietary API and may be removed in a future release
        throw new NotImplementedException();
                  ^
/home/dave/prog_code/CamCompSci/ID/project/Testing/readme_test/Weather/src/main/java/uk/ac/cam/groupseven/weatherapp/screens/MoreScreen.java:20: warning: NotImplementedException is internal proprietary API and may be removed in a future release
        throw new NotImplementedException();
                  ^
5 warnings

BUILD SUCCESSFUL in 6s
6 actionable tasks: 6 executed



gradle runApp gave an error:



FAILURE: Build failed with an exception.

* What went wrong:
Task 'runApp' not found in root project 'WeatherApp'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by SlightlySwissGuy** [comment]
I also tested these instructions in my existing IntelliJ-created directory and it worked

**Comment by SlightlySwissGuy** [comment]
![idea_files](https://user-images.githubusercontent.com/37239564/40280988-d6a6e390-5c4a-11e8-95de-31254a24da30.png)
Could be one of these I guess

**Comment by 101hawn** [comment]
Hmmmm. Could commit the gradlew wrapper to the github. Bit ugly but...

**Comment by 101hawn** [comment]
See if copying gradlew fixes?

**Comment by SlightlySwissGuy** [comment]
I tried copying across gradlew, then the entire gradle directory into my clone
Same error:


FAILURE: Build failed with an exception.

* What went wrong:
Task 'runApp' not found in root project 'WeatherApp'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by SlightlySwissGuy** [comment]
We found the problem:
git clone downloads master by default
switching to develop via a checkout made it work

**Comment by SlightlySwissGuy** [comment]
This brings us back to whether we should merge develop to master
