### ISSUE TITLE
Hours Screen has entries in random order

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#41]

**Comment by 101hawn** [comment]
Fixed by b83c4b8cfc43caa9bc9bb339a78d525c55fec5d8 ?

**Comment by SlightlySwissGuy** [comment]
![hours_random_order](https://user-images.githubusercontent.com/37239564/40280730-5419ee8e-5c47-11e8-834a-7d1dc8281247.png)
Sadly not
