### ISSUE TITLE
The arrow is weirded on some buttons

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#42]
![weirded_buttons](https://user-images.githubusercontent.com/37239564/40278855-563de9a0-5c28-11e8-8808-0ef4b5a99975.png)

**Comment by SlightlySwissGuy** [comment]
This is on both buttons of hours screen and the left button of days screen

**Comment by SlightlySwissGuy** [comment]
Also the left button says 24hr when it should say current forecast

**Comment by 101hawn** [comment]
Caused by bad merge I believe. Fixed?

**Comment by SlightlySwissGuy** [comment]
Yup, cheers
