### ISSUE TITLE
'7 day' screen is not actually 7 day - only 4 day

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#44]
This shouldn't (in theory) be too difficult
I'm thinking maybe we could call it 'upcoming days' because '4 day' sounds a bit rubbish

**Comment by ZGoriely** [comment]
done

**Comment by ZGoriely** [comment]
upcoming days is a bit long though for a label

**Comment by SlightlySwissGuy** [comment]
Hmm
I guess 4 day will have to do
