### ISSUE TITLE
Days and hours screens have (non-persistent) editable table cells

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#46]
This is more aesthetic than anything else as when you click off the table cell it goes back to the original, but:

**Comment by SlightlySwissGuy** [comment]
![editable_cells](https://user-images.githubusercontent.com/37239564/40312264-e5b64904-5d01-11e8-9f2d-be6295cdedee.png)

**Comment by 101hawn** [comment]
May also want to disable row selection? http://docs.oracle.com/javase/8/docs/api/javax/swing/JTable.html#setRowSelectionAllowed-boolean-

**Comment by SlightlySwissGuy** [comment]
dcce94c helped with this
entire rows are not editable

**Comment by SlightlySwissGuy** [comment]
But you can still select individual cells and type stuff
